/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "surface-container": "#edeeef",
        "tertiary-fixed-dim": "#66df75",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed-variant": "#004491",
        "on-tertiary-fixed-variant": "#00531a",
        "outline-variant": "#c2c6d4",
        "surface-tint": "#115cb9",
        "on-secondary-fixed": "#001f25",
        "on-tertiary": "#ffffff",
        "secondary-container": "#58e6ff",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#006573",
        "on-tertiary-container": "#6fe87c",
        "tertiary": "#004c17",
        "inverse-primary": "#acc7ff",
        "surface": "#f8f9fa",
        "on-surface-variant": "#424752",
        "tertiary-container": "#006722",
        "on-tertiary-fixed": "#002106",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#0056b3",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#a1efff",
        "secondary-fixed-dim": "#44d8f1",
        "on-secondary-fixed-variant": "#004e59",
        "primary": "#003f87",
        "tertiary-fixed": "#83fc8e",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "primary-fixed-dim": "#acc7ff",
        "on-surface": "#191c1d",
        "primary-fixed": "#d7e2ff",
        "secondary": "#006876",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#bbd0ff",
        "outline": "#727784",
        "on-primary-fixed": "#001a40",
        "on-background": "#191c1d",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
